server:
  port: 8803


spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:  #此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment:  #rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 192.168.232.129  #rabbitmq的地址，此处的这个地址是虚拟机CenterOS中的IP,用的docker
                port: 5672 #先检查端口，15672是插件的端口，在SpringBoot的配置文件中，应该使用5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用Exchage名称定义
          content-type: application/json #设置消息类型，本次用json，文本用：text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: sky  #分组号，stream消息rqbbitmq分组号，用于解决消息重复消费(不设置的话生成默认分组，分组流水号不同，分组号不同的组，消息可以重复消费)以及消息持久化()

eureka:
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10 #如果现在超过了10秒的时间间隔（默认90秒）
    instance-id: send-8803 #在信息列表时显示主机名称
    prefer-ip-address: true #访问路径变为IP地址
