server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka的服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gjtao1130/my-springcloud2020-config.git
          search-paths:     ##搜索目录
            - my-springcloud2020-config
      #读取分支
      label: master

#将服务注册进eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #http://eureka7002.com:7002/eureka
