#  gateway单独一个工程（不需要导入spring-boot-starter-web），这样启动完全没有问题。
#
#  springboot + gateway项目启动时报错：（是父子工程，gateway是一个子module）
#
#  Description:
#    Parameter 0 of method modifyRequestBodyGatewayFilterFactory in org.springframework.cloud.gateway.config.GatewayAutoConfiguration required a bean of type 'org.springframework.http.codec.ServerCodecConfigurer' that could not be found.
#  Action:
#    Consider defining a bean of type 'org.springframework.http.codec.ServerCodecConfigurer' in your configuration.
#    原因：
#    依赖冲突，spring-cloud-starter-gateway与spring-boot-starter-web和spring-boot-starter-webflux依赖冲突
#
#    解决：
#    排除 spring-boot-starter-web和spring-boot-starter-webflux依赖
#    注：排除 spring-boot-starter-web和spring-boot-starter-webflux依赖，gateway项目可以启动，但是功能可能丢失
#
#    所以我能想到的办法就是：gateway单独一个工程（不需要导入spring-boot-starter-web），这样启动完全没有问题。


server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh1  #路由的ID，要求唯一
          uri: http://localhost:8001  #匹配后提供服务的地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由

        - id: payment-routh2  #路由的ID，要求唯一
          uri: http://localhost:8001 #匹配后提供服务的地址
          predicates:
            - Path=/payment/get*  #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #注册进服务；列表
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


